[[pages]]
path = "streamlit_app.py"
name = "View Group Picks"
icon = "ğŸ€"

[[pages]]
path = "pages/make_picks.py"
name = "Pick your bracket"
icon = "ğŸ¯"

#[[pages]]
#path = "pages/pick_by_logos.py"
#name = "Pick your bracket by logos"
#icon = ":art:"